"""Runtime telemetry."""

from dromeus.telemetry.consensus import (
    COUNT_SKETCH_SIZE,
    ConsensusDistance,
    ConsensusSketchBuffer,
    ConsensusSketchError,
    ConsensusSketchMessage,
    ConsensusSketchPublisher,
    LiveConsensusTelemetry,
    count_sketch,
    exact_normalized_rms_distance,
    normalized_rms_consensus_distance,
)
from dromeus.telemetry.events import EventSink, JsonlEventSink, emit_event
from dromeus.telemetry.evidence import (
    EVIDENCE_VERSION,
    BenchmarkNodeReadyEvidence,
    ConsensusDistanceEvidence,
    EvidenceError,
    EvidenceLog,
    EvidenceRecord,
    RoundMetricsEvidence,
    RunFailedEvidence,
    TransferMessageSentEvidence,
    append_evidence,
    decode_evidence,
    encode_evidence,
)
from dromeus.telemetry.metrics import (
    JsonlMetricsPublisher,
    MetricsPublisher,
    RoundTiming,
)

__all__ = [
    "COUNT_SKETCH_SIZE",
    "EVIDENCE_VERSION",
    "BenchmarkNodeReadyEvidence",
    "ConsensusDistance",
    "ConsensusDistanceEvidence",
    "ConsensusSketchBuffer",
    "ConsensusSketchError",
    "ConsensusSketchMessage",
    "ConsensusSketchPublisher",
    "EventSink",
    "EvidenceError",
    "EvidenceLog",
    "EvidenceRecord",
    "JsonlEventSink",
    "JsonlMetricsPublisher",
    "LiveConsensusTelemetry",
    "MetricsPublisher",
    "RoundMetricsEvidence",
    "RoundTiming",
    "RunFailedEvidence",
    "TransferMessageSentEvidence",
    "append_evidence",
    "count_sketch",
    "decode_evidence",
    "emit_event",
    "encode_evidence",
    "exact_normalized_rms_distance",
    "normalized_rms_consensus_distance",
]
