name: CI

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v8.3.2

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Verify
        run: ./scripts/verify
